services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golden_pillow
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: 472-s-golden-pillow-backend-6510450925
    container_name: goldenpillow-backend
    restart: always
    ports:
      - "13889:13889"
    networks:
      - app-network
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql_data: # Define the volume used by the mysql service
  
networks:
  app-network:
    driver: bridge